### ISSUE TITLE
changing window width brings left-side menu out

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#1341] opened 2019-07-02 12:04 UTC
when changing window width the left hand side menu slides out.

**Comment by TrystanLea** [comment] 2019-07-03 09:23
Hey Dan, this is intended behaviour, when do you find it an issue?

**Comment by chaveiro** [comment] 2019-07-05 19:29
Generating an action (windows resize) that is not related in anything to a menu appearing seemed to me like  a bug.
If it's be design than it's a nuisance. 
You know what i mean if you use a 50" 4k monitor where you adjust window sizes regulary.

**Comment by danbates2** [comment] 2019-07-09 18:59
@TrystanLea bump :)

**Comment by TrystanLea** [comment] 2019-07-11 10:46
I dont agree that its a bug but one option could be to make a distinction that when the user clicks on the sidebar top level icon, which hides the sidebar that it then does not reopen when the window is expanded?

**Comment by danbates2** [comment] 2019-07-11 11:21
That'd be great!

**Comment by TrystanLea** [comment] 2019-07-11 15:34
Linking this issue to https://github.com/emoncms/emoncms/issues/1348 as very similar

**Comment by TrystanLea** [comment] 2019-09-03 15:27
This is now fixed in latest version

**Closed by TrystanLea** 2019-09-03 15:27 UTC
