### ISSUE TITLE
dashboard - graphs and feeds are not showing correct timezone from server

### ISSUE THREAD

**Issue by camelcamro** [emoncms/emoncms#1565] opened 2020-04-17 19:49 UTC
as since beginning ....
dashboard showing time from browsers timezone, and not from the server

so, the graphs are useless (eg: daily consume or a daily sun generating etc....
this is since years .. very sad about, and still seems to be not important to anyone ? :(
dashboard - graphs and feeds are not showing correct timezone from server

**Comment by borpin** [comment] 2020-04-17 19:54
Creating multiple issues for the same problem is unlikely to get it fixed any quicker.

https://github.com/emoncms/emoncms/issues/1060

**Comment by alexandrecuer** [comment] 2020-04-17 20:22
@camelcamro : why don't you propose something ? Most developpers involved are all very busy on different projects....
Moreover, from experience, time related problematics are not always so easy to code properly....

**Comment by TrystanLea** [comment] 2020-04-18 15:44
Closing this as its a duplicate of issues and discussions raised here:
https://github.com/emoncms/emoncms/issues/1060
https://github.com/emoncms/emoncms/pull/1545

**Closed by TrystanLea** 2020-04-18 15:44 UTC
