### ISSUE TITLE
Python Redis version missing

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1454] opened 2019-10-16 12:39 UTC
ref #1423 on Version 10.1.9

Not seeing Python Redis - sure it worked initially - on both EmonPi and UbuntuVM.

![image](https://user-images.githubusercontent.com/1322749/66919954-46412080-f01a-11e9-86b5-f0dada395193.png)

**Comment by TrystanLea** [comment] 2019-12-12 13:50
Same here, I think this was the code I disabled due to very slow performance, keeping this issue open as I think its a duplicate of https://github.com/emoncms/emoncms/issues/1464?

**Closed by TrystanLea** 2019-12-12 13:50 UTC
